### PR TITLE
Add support for metric variants

### PR DESCRIPTION
**Pull request by davecromberge**
Note this pull request is a continuation of and depends on: https://github.com/dalmatinerdb/dqe_idx/pull/11

### CODE REVIEW

**Comment by davecromberge** [comment]
@Licenser this also upgrades dqe_idx_ddb to the latest dqe_idx version.

**Comment by Licenser** [comment]
reading the changes I got a question, didn't you plan to rename metric_variants to metrics?

**Comment by davecromberge** [comment]
Yes I did, but planned to do it separately.  However, it will save us a lot of time to go through this whole process once.  I will hold off on this and further PRs until we are happy with this:
https://github.com/dalmatinerdb/dqe_idx/pull/12

**Comment by Licenser** [comment]
awesome much appriciated!

**Pull request merged**
